<?php

$_lang = array_merge($_lang ?? [], [
    'yandexmarket2'           => 'YandexMarket2',
    'yandexmarket2_menu_desc' => 'Export offers to XML',

    'ym2_pricelist'                 => 'Pricelist',
    'ym2_field'                     => 'Element',
    'ym2_attribute'                 => 'Attribute',
    'ym2_category'                  => 'Category',
    'ym2_condition'                 => 'Condition',
    'ym2_pricelist_err_nf'          => 'Pricelist is not found',
    'ym2_attribute_err_nf'          => 'Attribute is not found',
    'ym2_category_err_nf'           => 'Category is not found',
    'ym2_condition_err_nf'          => 'Condition is not found',
    'ym2_field_err_nf'              => 'Element is not found',
    'ym2_category_err_ae'           => 'Category already exists',
    'ym2_condition_column_err_ns'   => 'You need to specify a column',
    'ym2_condition_operator_err_ns' => 'You need to select an operator',
    'ym2_pricelist_name_err_ns'     => 'You need to input a name',
    'ym2_pricelist_type_err_ns'     => 'You need to select pricelist type',
    'ym2_pricelist_file_err_ae'     => 'Pricelist with same filename already exists',
    'ym2_field_err_valid'           => 'Invalid element value',
    'ym2_attribute_err_valid'       => 'Invalid attribute value',
    'ym2_pricelist_err_method'      => 'Unknown method',

    'ym2_field_type_0'  => 'text (without processing)',
    'ym2_field_type_1'  => 'root element',
    'ym2_field_type_2'  => 'shop element',
    'ym2_field_type_3'  => 'currencies list',
    'ym2_field_type_4'  => 'categories list',
    'ym2_field_type_5'  => 'offers list',
    'ym2_field_type_6'  => 'offer element',
    'ym2_field_type_7'  => 'category element',
    'ym2_field_type_10' => 'parent element',
    'ym2_field_type_11' => 'value from column',
    'ym2_field_type_12' => 'column in CDATA (with html tags)',
    'ym2_field_type_13' => 'product images',
    'ym2_field_type_14' => 'categories wrapper',
    'ym2_field_type_15' => 'offers wrapper',
    'ym2_field_type_19' => 'raw XML (without processing)',
    'ym2_field_type_20' => 'attributes only (empty element)',

    'ym2_msoptionsprice_options'     => 'Array of options with values',
    'ym2_fields_possible_elements'   => 'Possible elements',
    'ym2_fields_type_any_name'       => 'You can also enter any name',
    'ym2_resource_fields'            => 'Resource fields',
    'ym2_resource_additional_fields' => 'Additional offer fields',
    'ym2_ms2gallery_header'          => 'ms2Gallery resource images',
    'ym2_minishop2_fields'           => 'miniShop2 product fields',
    'ym2_minishop2_gallery'          => 'miniShop2 gallery',
    'ym2_minishop2_images'           => 'miniShop2 product images',
    'ym2_minishop2_options'          => 'miniShop2 options',
    'ym2_minishop2_vendor'           => 'miniShop2 vendor',
    'ym2_tv_fields'                  => 'Additional fields (TV)',
    'ym2_category_fields'            => 'Parent category fields (standard)',
    'ym2_category_pagetitle'         => 'Parent category title',
    'ym2_category_name'              => 'Format for any other parent field',
    'ym2_category_tv'                => 'Additional category fields (TV)',
    'ym2_category_tv_name'           => 'Format for category TV fields',
    'ym2_msop2_modification_fields'  => 'msOptionsPrice2 modification fields',

    'ym2_offer_field_url'   => 'Full product link',
    'ym2_offer_field_price' => 'Price including ms2 plugins and msOp2 mods',
    'ym2_offer_field_image' => 'Product image with full link (from image field)',

    'ym2_xml_file_existed' => 'File %s already exists and will be overwritten',
    'ym2_xml_file_writing' => 'File writing process started',
    'ym2_xml_file_written' => 'File %s was written successfully',

    'ym2_debug_mode_enabled'             => 'Debug mode is enabled. The log will be more detailed',
    'ym2_debug_categories_written'       => 'Categories written: %d',
    'ym2_debug_offers_written'           => 'Products written: %d',
    'ym2_debug_undefined_type'           => 'Unknown type "%s" for field "%s" (ID: %d)',
    'ym2_debug_empty_value'              => 'Empty value for required element %s',
    'ym2_debug_empty_raw'                => 'Empty raw XML, missing element %s',
    'ym2_debug_undefined_attribute_type' => 'Unknown type "%s" for attribute "%s" (ID: %d)',
    'ym2_debug_empty_categories'         => 'Empty list of categories in field "%s" (ID: %d)',
    'ym2_debug_empty_offers'             => 'Empty list of products in field "%s" (ID: %d)',

    'ym2_debug_offers_not_found'            => ' No matching offers found ',
    'ym2_debug_suitable_offers'             => ' Suitable offers: ',
    'ym2_debug_suitable_categories'         => ' Suitable categories: ',
    'ym2_debug_possible_categories_plugins' => ' Possibly using category conditions from plugins ',
    'ym2_debug_possible_offers_plugins'     => ' Possibly using offer conditions from plugins ',
    'ym2_debug_element_not_found'           => ' Element not found ',

    'ym2_debug_pdotools_not_found'        => 'pdoTools not found. The code will be parsed by MODX parser',
    'ym2_debug_add_offers_condition'      => 'Added id IN (offers ids) condition for categories',
    'ym2_debug_joined_table_with_columns' => 'Joined table `%s` with columns "%s" to %s',
    'ym2_debug_ms2gallery_error'          => 'Failed to load ms2Gallery. Check your margin settings.',
    'ym2_debug_msop2_modification'        => 'For modifications to msOptionsPrice2 in the price list in offer setup, add ":msop2" to the resource class, example "msProduct:msop2"',
    'ym2_debug_add_categories_condition'  => 'Added %s IN (select id from parentsQuery) condition for products',
    'ym2_debug_unknown_class'             => 'Unknown class %s. Load the model in your plugin for the ym2OnBeforeOffersQuery event or contact support.',
    'ym2_debug_unknown_operator'          => 'Unknown operator for condition',
    'ym2_debug_query_add_categories'      => 'Missing categories added to category query: %s',

    'ym2_marketplace_yandex.market' => 'Yandex Market',
    'ym2_marketplace_google.rss20'  => 'Google RSS 2.0 (Merchant center, FB)',
]);
