export const MODX_ICONS = {
    complete: 'icon icon-check',
    cancel: 'icon icon-times-circle',
    close: 'icon icon-times',
    delete: 'icon icon-times-circle', // delete (e.g. v-chip close)
    clear: 'icon icon-times-circle', // delete (e.g. v-chip close)
    success: 'icon icon-check-circle',
    info: 'icon icon-info-circle',
    warning: 'icon icon-exclamation',
    error: 'icon icon-exclamation-triangle',
    prev: 'icon icon-chevron-left',
    next: 'icon icon-chevron-right',
    checkboxOn: 'icon icon-check-square',
    checkboxOff: 'icon icon-square-o',
    checkboxIndeterminate: 'icon icon-minus-square',
    delimiter: 'icon icon-circle', // for carousel
    sort: 'icon icon-sort-up',
    expand: 'icon icon-chevron-down',
    menu: 'icon icon-bars',
    subgroup: 'icon icon-caret-down',
    dropdown: 'icon icon-caret-down',
    radioOn: 'icon icon-dot-circle-o',
    radioOff: 'icon icon-circle-o',
    edit: 'icon icon-pencil',
    ratingEmpty: 'icon icon-star-o',
    ratingFull: 'icon icon-star',
    ratingHalf: 'icon icon-star-half-o',
    loading: 'icon icon-refresh',
    first: 'icon icon-step-backward',
    last: 'icon icon-step-forward',
    unfold: 'icon icon-angle-double-down',
    file: 'icon icon-paperclip',
    plus: 'icon icon-plus',
    minus: 'icon icon-minus',
}