<?php

$lexicon = [
    //header
    'YandexMarket2'                                      => 'YandexMarket2',
    'uploading offers in XML for Yandex Market and more' => 'выгрузка предложений в XML для Яндекс Маркет и не только',

    // prcelists page
    'Displaying {pageStart}-{pageStop} of {itemsLength}' => 'Показано {pageStart}-{pageStop} из {itemsLength}',
    'You have {total} {pricelists}'                      => 'У вас {total} {pricelists}',
    'pricelist|pricelists|pricelists'                    => 'прайс-лист|прайс-листа|прайс-листов',
    'Add your first pricelist'                           => 'Добавьте свой первый прайс-лист',
    'Add pricelist'                                      => 'Добавить прайс-лист',
    'Adding a pricelist'                                 => 'Добавление прайс-листа',
    'Marketplace'                                        => 'Маркетплейс',
    'You can add new ones, see documentation'            => 'Вы можете добавить новые, см. документацию',
    'Pricelist name'                                     => 'Название прайс-листа',
    'Pricelist filename'                                 => 'Название файла',
    'No pricelists yet'                                  => 'Пока ещё нет прайс-листов',
    'File not generated yet'                             => 'Файл ещё не сгенерирован',
    'Cron only'                                          => 'Только cron',
    'On the fly'                                         => 'На лету',
    'Manually'                                           => 'Вручную',
    'Need to generate the file!'                         => 'Нужно сгенерировать файл!',
    'File generation'                                    => 'Генерация файла',
    'Cancel'                                             => 'Отмена',
    'Return'                                             => 'Вернуться',
    'Save'                                               => 'Сохранить',
    'Add'                                                => 'Добавить',
    'Yes'                                                => 'Да',
    'No'                                                 => 'Нет',
    'refresh'                                            => 'Обновить',
    'Sort by'                                            => 'Сортировать по',
    'Show by'                                            => 'Показывать по',
    'Edit pricelist'                                     => 'Редактировать прайс-лист',
    'Delete pricelist'                                   => 'Удалить прайс-лист',
    'All goods'                                          => 'Все товары',
    'ID'                                                 => 'ID',
    'Name'                                               => 'Название',
    'Pricelist type'                                     => 'Тип прайс-листа',
    'Filename'                                           => 'Файл',
    'Generation type'                                    => 'Формирование',
    'Generated at'                                       => 'Сформирован',
    'Active'                                             => 'Активен',
    'Actions'                                            => 'Действия',

    'Are you sure you want to remove the pricelist {pricelist}? This action is irreversible' => 'Вы действительно хотите удалить прайс-лист {pricelist} ? Это действие безвозвратное',

    // pricelist common
    'Shop settings' => 'Настройки магазина',
    'Categories settings' => 'Настройки категорий',
    'Offers settings' => 'Настройки предложений',
    'File generation and parameters' => 'Выгрузка и параметры',
    'Enable preview' => 'Включить предпросмотр',
    'Disable preview' => 'Отключить предпросмотр',
    'To all pricelists' => 'Ко всем прайс-листам',
    'XML element preview' => 'Предпросмотр XML элемента',
    'Automatically updated on any change' => 'Автоматически обновляется при любом изменении',
    'Loading an XML element' => 'Загружается XML элемент',
    'class not found in the system' => 'класс не найден в системе',

    'Perhaps the php module <i>libxml</i> is disabled or php is started with the flag <i>--disable-xmlwriter</i>' => 'Возможно, отключён php модуль <i>libxml</i> или php запущен с флагом <i>--disable-xmlwriter</i>',

    //pricelist shop
    'Shop main fields settings'                                                              => 'Настройки основных полей магазина',
    'Required fields are marked with an asterisk.'                                           => 'Обязательные поля отмечены звёздочкой.',
    'Do not forget to save your changes.'                                                    => 'Не забывайте сохранять изменения.',
    'Empty fields will not be included in the file.'                                         => 'Пустые поля не попадут в файл.',
    'The save changes button appears after you start editing.'                               => 'Кнопка сохранения изменений появляется после начала редактирования.',

    //pricelist offer
    'The main criteria for generating a request'                                             => 'Основные критерии для формирования запроса',
    'When changes are made, an offer preview is updated'                                     => 'При изменениях обновляется предпросмотр предложения',
    'Change the offer in the preview'                                                        => 'Поменять предложение в предпросмотре',
    'Class for fetching offers (class_key from resource table)'                              => 'Класс для выборки предложений (class_key из таблицы ресурсов)',
    'Be careful with the setting. For simple resources, specify modDocument'                 => 'Аккуратнее с настройкой. Для простых ресурсов укажите modDocument',
    'Attribute'                                                                              => 'Атрибут',
    'Resource class'                                                                         => 'Класс ресурса',
    'Enable class_key editing'                                                               => 'Включить редактирование class_key',
    'Cancel changes'                                                                         => 'Отменить изменения',
    'Save changes'                                                                           => 'Сохранить изменения',
    'Conditions for goods'                                                                   => 'Условия по товарам',
    'All product fields are available, including TV fields, ms2 options.'                    => 'Доступны все поля товаров, включая ТВ-поля, опции ms2.',
    'The component will automatically join the columns specified.'                           => 'Компонент автоматически присоединит указанные столбцы.',
    'If you need to add third-party components - contact support'                            => 'Если нужно присоединить сторонние компоненты - обратитесь в поддержку',
    'Set up offers fields'                                                                   => 'Настройка полей предложений',
    'Interactive mode for adding and editing fields'                                         => 'Интерактивный режим добавления и редактирования полей',
    'Element with type "offer" not found. The "offers" element may have been removed.'       => 'Не найден элемент с типом offer(6). Возможно, был удалён элемент offers.',
    'Add an offers element or recreate the pricelist.'                                       => 'Добавьте элемент предложений или пересоздайте прайс-лист.',

    // pricelist categories
    'Categories involved in file generation - nested categories must also be selected' => 'Категории, участвующие в выгрузке - вложенные тоже нужно выбирать',
    'If nothing is selected, the categories of all matching products will be unloaded' => 'Если ничего не выбрать, то будут выгружены категории всех подходящих товаров',
    'Category element settings in XML' => 'Настройки элемента категории в XML',
    'An element of type "category" was not found.' => 'Не найден элемент с типом category.',
    'The categories element may have been removed or is not needed in the file.' => 'Возможно, был удалён элемент categories или он не нужен в файле.',
    'Only the conditions will be considered' => 'Будут учитываться только условия.',

    // pricelist generation
    'Main parameters of pricelist generation' => 'Основные параметры выгрузки прайс-листа',
    'All fields are required' => 'Все поля обязательны к заполнению',
    'Pricelist type (set when creating)' => 'Тип прайс-листа (задаётся при создании)',
    '(specify with xml extension)' => '(укажите вместе с расширением xml)',
    'The file will be available at {fileUrl}' => 'Файл будет доступен по адресу {fileUrl}',
    'File generation mode' => 'Режим формирования файла',
    'Regenerate the file every N minutes, even if there were no changes' => 'Обновлять файл каждые N минут, даже если не было изменений',
    '0 - no additional updates. To update the file once a day, specify 1440' => '0 - без дополнительных обновлений. Чтобы обновлять файл раз в сутки укажите 1440',
    'Pricelist is active (monitoring changes in settings and related products)' => 'Прайс-лист активен (отслеживаются изменения настроек и связанных товаров)',
    'Pricelist is NOT active (activate after setup is complete)' => 'Прайс-лист НЕ активен (активируйте после завершения настройки)',
    'Revert all changes' => 'Отменить все изменения',
    'File root element settings' => 'Настройки корневого элемента файла',
    'Products or settings have changed. The file needs to be regenerated!' => 'Изменились товары или настройки. Файл нужно перегенерировать!',
    'Previous pricelist generated in {generatedAt}' => 'Предыдущий прайс-лист сформирован {generatedAt}',
    'Link to file:' => 'Ссылка на файл:',
    'The file will open in a new window' => 'Файл откроется в новом окне',
    'The pricelist has not yet been formed' => 'Прайс-лист ещё ни разу не был сформирован',
    'The existing file will be overwritten' => 'Существующий файл будет перезаписан',
    'Generate a new file' => 'Сформировать новый файл',
    'File generation log' => 'Лог генерации файла',
    'Are you sure you want to regenerate the file?' => 'Вы действительно хотите перегенерировать файл?',
    'File generation log will appear here' => 'Здесь появится лог генерации файла',
    'Only manually in the admin panel (manual mode)' => 'Только вручную в админ-панели (ручной режим)',
    'If a cron task is set, then this pricelist will not be included' => 'Если установлена крон задача - то этот прайслист туда не попадёт',
    'When changing products on the fly (for small sites)' => 'При изменении товаров на лету (для небольших сайтов)',
    'The pricelist will be formed immediately. Force update by cron' => 'Прайс-лист будет формироваться сразу. Принудительное обновление по cron',
    'By cron when changing products (recommended)' => 'По cron при изменении товаров (рекомендуется)',
    'Install a cron job every minute at /core/components/yandexmarket2/cron/generate.php' => 'Поставьте ежеминутную крон-задачу на /core/components/yandexmarket2/cron/generate.php',
];

$_lang = array_merge($_lang ?? [], array_combine(array_map(static function (string $key) {
    return 'yandexmarket2_vuetify_'.$key;
}, array_keys($lexicon)), $lexicon));